name: CI / CD

on:
  push:
    branches:
      - main
      - release
  merge_group:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out registry infra setup
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          path: ./registry-infra

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          scope: "@subtopia-algo"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.7.1

      - name: Run AlgoKit LocalNet
        run: |
          poetry run pipx install algokit
          algokit localnet start

      - name: Setup localnet registry
        run: |
          cp .env.template .env
          cd registry-infra
          poetry install
          cat ${{ github.workspace }}/.env
          LOCALNET_APP_IDS_PATH=${{ github.workspace }}/.env poetry run python3 admin_scripts/deploy_localnet_infra.py
          cat ${{ github.workspace }}/.env

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run test:integration
