name: CI / CD

on:
  push:
    branches:
      - main
      - release
  merge_group:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          scope: "@subtopia-algo"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Setup Subtopia Registry
        uses: ./.github/actions/setup-subtopia-registry
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          repository: subtopia-algo/subtopia-contracts
          path: ./registry-infra
          node-version: 18
          python-version: 3.11
          poetry-version: 1.7.1

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run test:integration
